name = "Lumo Optimized"
author = "Luca Silverentand"
version = "1.0.0"
description = "A performance-focused Fabric modpack for Minecraft 1.21.8 optimized for low-end devices, integrated graphics, and older hardware."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb7273f40e80f69b0a4d0fe71f4a3b79b68f59d3b1ca75071de2b3b96ba7826e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.3", "1.21.4", "1.21.5", "1.21.6", "1.21.7"]
