name = "Lumo Optimized"
author = "Luca Silverentand"
version = "1.1.0"
description = "A performance-focused Fabric modpack for Minecraft 1.21.8 optimized for low-end devices, integrated graphics, and older hardware."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc3022aee5358f4b685c6fb72fbb0b482ad39598d2311b1985d3220dccbbe0dc"

[versions]
fabric = "0.19.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.3", "1.21.4", "1.21.5", "1.21.6", "1.21.7"]
